mouths=c("GEN","FEB","MAR","APR","MAG","GIU","LUG","AGO","SET","OTT","NOV","DIC")
length(mouths)
sample(mouths, 1, replace = TRUE)
sample(mouths, 3, replace = TRUE)
sample(mouths, 3, replace = FALSE)
sample(mouths, 11, replace = TRUE)
sample(mouths, 11, replace = FALSE)
y=sample(mouths, 11, replace = TRUE)
anyDuplicated(y)
duplicated(y)